// template/framework/vue/src/entries/options/App.vue
<template>
  <main>
    <PageHeader> Options </PageHeader>
  </main>
</template>

<script setup>
import PageHeader from "~/components/PageHeader.vue";
</script>

<style>
main {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// template/framework/svelte-ts/src/entries/options/App.svelte
<script lang="ts">
import PageHeader from "~/lib/PageHeader.svelte";
</script>

<main>
  <PageHeader> Options </PageHeader>
</main>

<style>
main {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
